extends:
  - airbnb
  - airbnb/hooks
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:jest-dom/recommended
  - plugin:prettier/recommended

env:
  browser: true
  node: true
  jest: true

plugins:
  - simple-import-sort

rules:
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  import/order: off
